name: Code Quality Control

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']

jobs:
  quality-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit black pylint

    - name: Run pylint
      run: |
        pylint --rcfile=tools/lint/.pylintrc --fail-under=6.5 scirex/
    
    - name: Run black
      run: |
        black --check scirex/
